# @package _global_
actor_rollout_ref:
  actor:
    eplb_enable: false
    megatron:
      router_replay:
        mode: R3
  rollout:
    enable_rollout_routing_replay: true
trainer:
  experiment_name: collect
  eplb_load_collection_enable: true

